import json
import anthropic


class ClaudeClient:
    def __init__(self, api_key: str):
        self._client = anthropic.Anthropic(api_key=api_key)

    def judge_rca_eligibility(
        self, summary: str, description: str, priority: str, labels: list[str]
    ) -> dict:
        prompt = f"""You are screening engineering bugs to determine if they warrant a Root Cause Analysis.

Flag as RCA-eligible if the bug shows evidence of any of:
- Non-obvious root cause (not a trivial config error or typo)
- Cascading or system-wide failure (multiple services/components affected)
- Required significant investigation or manual intervention to resolve
- Could recur without a design or process change
- Data loss, corruption, or integrity risk
- Customer-visible functional failure

Priority scope: P1, P2, P3, and unset priority all qualify.
Do NOT flag if: root cause was immediately obvious and the fix was trivial.

Respond with JSON only: {{"eligible": true/false, "reason": "...", "confidence": "high/medium/low"}}

Bug summary: {summary}
Priority: {priority}
Labels: {labels}
Description: {description}"""

        message = self._client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=256,
            messages=[{"role": "user", "content": prompt}],
        )
        return json.loads(message.content[0].text.strip())

    def analyze_rca_gaps(
        self, rca_text: str, fix_text: str, bug_summary: str, bug_description: str
    ) -> dict:
        prompt = f"""You are an expert engineering coach reviewing a Root Cause Analysis.

Perform two analyses and return JSON:

1. RUBRIC CHECK — evaluate whether each section is present and substantive:
   - "What happened?": describes the observable failure (not just "bug occurred")
   - "How did it happen?": technical root cause, not just symptoms
   - "How was it missed?": specific process/knowledge gap named (not generic "missed in review")
   - "How was it fixed?": code-level or config-level fix described
   - "Prevention": concrete action items (not generic "add tests" or "be more careful")

2. FIVE WHYS — independently construct the causal chain from the bug details, then map each "why" against the RCA content. Flag where the chain was cut short.

Return JSON only (no extra text):
{{
  "rubric_gaps": ["list of specific gap descriptions, empty if none"],
  "five_whys_chain": [
    {{"why": "why description", "covered": true/false, "note": "brief note if partially covered or missing"}}
  ],
  "deepest_unanswered_why": "the root cause the RCA did not reach, or empty string if fully covered",
  "comment_markdown": "the full Jira comment to post, formatted with sections RUBRIC GAPS and 5 WHYS ANALYSIS and a SUGGESTED ADDITION if deepest_unanswered_why is non-empty. Use ✅/⚠️/❌ markers. End with a horizontal rule and: _Generated by rca-bot. Review and refine before tonight's forum._"
}}

Bug summary: {bug_summary}
Bug description: {bug_description}

RCA content:
{rca_text}

Fix description:
{fix_text}"""

        message = self._client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=2048,
            messages=[{"role": "user", "content": prompt}],
        )
        return json.loads(message.content[0].text.strip())
